# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_INF=y
CONFIG_AC_CHARGE_LOG_LEVEL_DBG=y

# Enable AC charge library
CONFIG_PWM=y
CONFIG_ADC=y
CONFIG_SMF=y
CONFIG_LIB_AC_CHARGE=y

# Enable the shell
CONFIG_SHELL=y
